---
- name: 基础软件安装
  yum: name={{item}} state=present
  with_items:
     - gcc
     - gcc-c++
     - wget
     - lrzsz
     - telnet
     - net-tools
     - epel*
     - vim 
     - unzip
     - ntpdate
     - yum-utils
     - device-mapper-persistent-data
     - conntrack-tools
     - libseccomp
     - libtool-ltdl

- name: 关闭防火墙
  service: name=firewalld state=stopped enabled=no

- name: 开启ntpdate
  service: name=ntpdate state=started enabled=yes

- name: ntp同步
  cron: name='ntpdate' minute="20" job="/usr/sbin/ntpdate time7.aliyun.com"

- name: ulimit设置
  shell: echo "* soft nofile 65536" >> /etc/security/limits.conf && echo "* hard nofile 65536" >> /etc/security/limits.conf  && echo "* soft nproc 65536"  >> /etc/security/limits.conf && echo "* hard nproc 65536"  >> /etc/security/limits.conf && echo "* soft  memlock  unlimited"  >> /etc/security/limits.conf && echo "* hard memlock  unlimited"  >> /etc/security/limits.conf

- name: 关闭selinux
  shell: sed -i "s/^SELINUX=enforcing/SELINUX=disabled/g" /etc/sysconfig/selinux && setenforce 0 && sed -i "s/^SELINUX=enforcing/SELINUX=disabled/g" /etc/selinux/config   && sed -i "s/^SELINUX=permissive/SELINUX=disabled/g" /etc/sysconfig/selinux  && sed -i "s/^SELINUX=permissive/SELINUX=disabled/g" /etc/selinux/config   && setenforce  0 

  - name: hosts 分发
  template:  src=/srv/ansible/roles/basic/templates/hosts.j2  dest=/etc/hosts

- name:  开启 forward
  shell: modprobe br_netfilter && echo net.ipv4.ip_forward = 1 >  /etc/sysctl.d/k8s.conf && echo net.bridge.bridge-nf-call-ip6tables = 1  >> /etc/sysctl.d/k8s.conf && echo net.bridge.bridge-nf-call-iptables = 1  >> /etc/sysctl.d/k8s.conf  && sysctl -p /etc/sysctl.d/k8s.conf

- name: 开机自启动 forward
  shell: chmod +x /etc/rc.d/rc.local  && echo modprobe br_netfilter  >>/etc/rc.d/rc.local  && echo sysctl -p /etc/sysctl.d/k8s.conf   >>/etc/rc.d/rc.local

- name: 关闭swap交换分区
  shell: swapoff -a   && sed -i 's/.*swap.*/#&/' /etc/fstab

- name: 设置主机名称
  shell: hostname {{name}}   && echo {{name}}  >/etc/hostname

